-- Criação da tabela de leituras automáticas do medidor smart
CREATE TABLE IF NOT EXISTS leitura_energia (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_execucao TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    data_leitura TIMESTAMP WITH TIME ZONE,
    valor_extraido DECIMAL(12, 3),
    medidor_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Habilitar RLS (Recomendado)
ALTER TABLE leitura_energia ENABLE ROW LEVEL SECURITY;

-- Política para permitir inserção via API (Ajuste conforme necessário)
CREATE POLICY "Permitir inserção anônima" ON leitura_energia
    FOR INSERT 
    WITH CHECK (true);

-- Política para leitura
CREATE POLICY "Permitir leitura para todos autenticados" ON leitura_energia
    FOR SELECT
    USING (true);
